"""
Meta Account Diagnostics — Streamlit Dashboard
Generated by /meta-diagnostics. Reads ~/meta-diagnostics/results.json at runtime.
Do not edit this file — re-run /meta-diagnostics to regenerate.
"""

import json
from pathlib import Path
from datetime import date

import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd

RESULTS_PATH = Path.home() / "meta-diagnostics" / "results.json"


def _to_float(v) -> float:
    """Parse a numeric value that may arrive as int, float, or a formatted string like '$216,029'."""
    if isinstance(v, (int, float)):
        return float(v)
    if v is None:
        return 0.0
    return float(str(v).replace("$", "").replace(",", "").strip() or 0)


def _fmt_usd(v: float) -> str:
    """Format as USD currency. Uses 4 decimals for sub-penny values, 2 otherwise."""
    if v is None:
        return "—"
    if abs(v) < 0.01:
        return f"${v:,.4f}"
    return f"${v:,.2f}"

VERDICT_COLORS = {
    "HEALTHY":           "#22c55e",
    "WARNING":           "#f59e0b",
    "CRITICAL":          "#ef4444",
    "INSUFFICIENT_DATA": "#6b7280",
}

VERDICT_BG = {
    "HEALTHY":           "#f0fdf4",
    "WARNING":           "#fffbeb",
    "CRITICAL":          "#fef2f2",
    "INSUFFICIENT_DATA": "#f3f4f6",
}


def load_results() -> dict:
    if not RESULTS_PATH.exists():
        st.error(f"Results file not found at {RESULTS_PATH}. Run /meta-diagnostics first.")
        st.stop()
    with open(RESULTS_PATH) as f:
        return json.load(f)


def verdict_badge(verdict: str) -> str:
    color = VERDICT_COLORS.get(verdict, "#6b7280")
    return f'<span style="background:{color};color:white;padding:3px 10px;border-radius:4px;font-weight:700;font-size:13px">{verdict}</span>'


def analysis_card(title: str, verdict: str, meaning: str, action: str, chart_fn):
    bg = VERDICT_BG.get(verdict, "#f9fafb")
    st.markdown(f"""
<div style="border:1px solid #e5e7eb;border-radius:8px;padding:20px;margin-bottom:20px;background:{bg}">
<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px">
<h3 style="margin:0;font-size:16px">{title}</h3>
{verdict_badge(verdict)}
</div>
""", unsafe_allow_html=True)
    chart_fn()
    st.markdown(f"**What it means:** {meaning}")
    st.markdown(f"**Action:** {action}")
    st.markdown("</div>", unsafe_allow_html=True)


def chart_test_and_learn(data: dict):
    ads = data.get("ads", [])
    if not ads:
        st.info("No ad data available.")
        return
    df = pd.DataFrame(ads)
    df["spend"] = pd.to_numeric(df.get("spend", 0), errors="coerce").fillna(0)
    df["cpa"] = pd.to_numeric(df.get("cpa", 0), errors="coerce").fillna(0)
    df["zone"] = df.get("zone", "Green")

    zone_color_map = {"Red": "#ef4444", "Green": "#22c55e", "Purple": "#a855f7"}
    fig = px.scatter(
        df, x="spend", y="cpa", color="zone",
        color_discrete_map=zone_color_map,
        hover_data=["name"],
        labels={"spend": "Lifetime Spend ($)", "cpa": data.get("cpa_label", "CPA ($)"), "zone": "Zone"},
        log_x=True,
        title="",
    )
    fig.update_traces(marker=dict(size=9, opacity=0.8))
    fig.update_layout(margin=dict(t=10, b=10), height=320)
    st.plotly_chart(fig, use_container_width=True)


def chart_creative_allocation(data: dict):
    ads = data.get("ads", [])
    if not ads:
        st.info("No ad data available.")
        return
    df = pd.DataFrame(ads)
    df["spend"] = pd.to_numeric(df.get("spend", 0), errors="coerce").fillna(0)
    df["tier"] = df.get("tier", "Other")
    # Sort by spend descending — cpa ascending is wrong because cpa=0 (no conversions) sorts first
    df = df[df["spend"] > 0].sort_values("spend", ascending=False)

    top_n = 40
    df_top = df.head(top_n)
    tier_color_map = {"Top 1%": "#a855f7", "Top 10%": "#6366f1", "Other": "#d1d5db"}
    fig = px.bar(
        df_top, x="name", y="spend",
        color="tier", color_discrete_map=tier_color_map,
        labels={"name": "Ad", "spend": "Spend ($)", "tier": "Tier"},
        title=f"Top {len(df_top)} ads by spend (of {len(df)} active in window)",
    )
    fig.update_layout(xaxis_tickangle=-45, margin=dict(t=30, b=80), height=380, xaxis_showticklabels=False)

    # Annotation: how many ads account for 50% of total spend (from full sorted list)
    total_spend = df["spend"].sum()
    cumulative = df["spend"].cumsum()
    ads_to_50pct = int((cumulative <= total_spend * 0.5).sum()) + 1
    fig.add_annotation(
        xref="paper", yref="paper", x=0.99, y=0.95, showarrow=False,
        text=f"<b>{ads_to_50pct} ads = 50% of spend</b>",
        bgcolor="rgba(255,255,255,0.8)", bordercolor="#d1d5db", borderwidth=1,
    )
    st.plotly_chart(fig, use_container_width=True)


def chart_old_creative(data: dict):
    monthly = data.get("monthly_spend_by_age", [])
    top_ads = data.get("monthly_top_ads_by_age", [])  # absent in older results.json — degrade gracefully
    top_n   = data.get("top_ads_per_bucket", 5)
    if not monthly:
        st.info("No age data available.")
        return
    df = pd.DataFrame(monthly)
    age_cols = [c for c in ["New (0-30d)", "Mid (31-60d)", "Aging (61-90d)", "Old (90d+)"] if c in df.columns]
    colors = {"New (0-30d)": "#1d4ed8", "Mid (31-60d)": "#60a5fa", "Aging (61-90d)": "#fcd34d", "Old (90d+)": "#d1d5db"}

    top_by_month = {row["month"]: row.get("buckets", {}) for row in top_ads}

    def render_top_list(month: str, bucket: str) -> str:
        items = top_by_month.get(month, {}).get(bucket, [])
        if not items:
            return "<i>No ads in this bucket</i>"
        return "<br>".join(
            f"{it['rank']}. {it['name']} — ${it['spend']:,.0f}"
            for it in items
        )

    fig = go.Figure()
    for col in reversed(age_cols):
        if top_by_month:
            customdata = [[render_top_list(m, col)] for m in df["month"]]
            hovertemplate = (
                f"<b>{col}</b> · %{{x}}<br>"
                f"Bucket spend: $%{{y:,.0f}}<br><br>"
                f"<b>Top {top_n} ads by spend:</b><br>"
                f"%{{customdata[0]}}<extra></extra>"
            )
        else:
            customdata = None
            hovertemplate = f"<b>{col}</b> · %{{x}}<br>Bucket spend: $%{{y:,.0f}}<extra></extra>"

        fig.add_bar(
            name=col,
            x=df["month"],
            y=df[col],
            marker_color=colors.get(col, "#9ca3af"),
            customdata=customdata,
            hovertemplate=hovertemplate,
        )

    fig.update_layout(
        barmode="stack", title="", height=300, margin=dict(t=10, b=10),
        legend=dict(orientation="h", y=-0.2),
        hoverlabel=dict(bgcolor="white", font_size=12, font_family="monospace", align="left"),
    )
    st.plotly_chart(fig, use_container_width=True)
    st.caption(
        "Each bar shows spend that ran during that calendar month, broken down by how old each ad was at that time. "
        "An ad created in December appears in the New (0–30d) bucket for its December spend, "
        "Mid (31–60d) bucket for its February spend, and so on. "
        "The X-axis is the month spend occurred — not the month the ad launched."
    )


def chart_creative_churn(data: dict):
    cohorts = data.get("cohort_spend_by_month", [])
    warnings = data.get("data_warnings", [])
    if not cohorts:
        msg = warnings[0] if warnings else "Cohort spend data unavailable — rerun the diagnostic with meta_get_ad_monthly_spend connected."
        st.info(msg)
        launches = data.get("monthly_launches", [])
        if launches:
            df_l = pd.DataFrame(launches)
            fig = px.bar(df_l, x="month", y="count",
                         title="Monthly launch volume (cohort spend curves unavailable)",
                         labels={"count": "Ads launched", "month": "Month"})
            fig.update_layout(height=280, margin=dict(t=30, b=10))
            st.plotly_chart(fig, use_container_width=True)
        return
    if warnings:
        st.caption(f"⚠️ {warnings[0]}")
    df = pd.DataFrame(cohorts).fillna(0)
    months = df["month"].tolist()
    cohort_cols = [c for c in df.columns if c != "month"]
    fig = go.Figure()
    palette = px.colors.qualitative.Set2
    for i, col in enumerate(cohort_cols):
        series = df[col].tolist()
        try:
            first_idx = next(idx for idx, v in enumerate(series) if v > 0)
        except StopIteration:
            continue
        fig.add_scatter(
            name=col,
            x=months[first_idx:],
            y=series[first_idx:],
            mode="lines",
            stackgroup="one",
            line=dict(color=palette[i % len(palette)]),
        )
    fig.update_layout(
        title="", height=320, margin=dict(t=10, b=10),
        legend=dict(orientation="h", y=-0.25),
        xaxis=dict(type="category", title="Month"),
        yaxis=dict(title="Spend (USD)"),
    )
    st.plotly_chart(fig, use_container_width=True)


def chart_slugging_rate(data: dict):
    windows = data.get("windows", [])
    if not windows:
        st.info("No slugging data available.")
        return

    top_pct    = data.get("winner_top_percentile", 0.20)
    min_spend  = data.get("winner_min_spend", 300)
    window_d   = data.get("window_days", 60)
    target_rate = top_pct * 100
    motion_ctx  = data.get("motion_avg_hit_rate_for_context")

    st.caption(
        f"Winners = top {int(top_pct*100)}% CPA within each {window_d}-day cohort window "
        f"(spend ≥ ${min_spend} + ≥1 conversion). "
        "Each window's threshold is computed only from ads launched in that window — "
        "older cohorts don't drag down the bar for newer ones."
    )

    df = pd.DataFrame(windows)
    labels = df["label"].tolist()

    hit_rates    = df["hit_rate_pct"].tolist() if "hit_rate_pct" in df.columns else [0] * len(df)
    winner_spend = df["winner_spend"].tolist() if "winner_spend" in df.columns else [0] * len(df)
    losing_spend = df["losing_qualified_spend"].tolist() if "losing_qualified_spend" in df.columns else [0] * len(df)
    wasted_spend = df["wasted_spend"].tolist() if "wasted_spend" in df.columns else [0] * len(df)

    fig = go.Figure()
    fig.add_bar(
        name="Winner spend",
        x=labels, y=winner_spend,
        marker_color="#1d4ed8",
        customdata=hit_rates,
        hovertemplate="<b>%{x}</b><br>Winner spend: $%{y:,.0f}<br>Hit rate: %{customdata:.1f}%<extra></extra>",
    )
    fig.add_bar(
        name="Qualified non-winner spend",
        x=labels, y=losing_spend,
        marker_color="#f59e0b",
        hovertemplate="<b>%{x}</b><br>Non-winner qualified: $%{y:,.0f}<extra></extra>",
    )
    fig.add_bar(
        name="Wasted spend (0 conversions)",
        x=labels, y=wasted_spend,
        marker_color="#ef4444",
        hovertemplate="<b>%{x}</b><br>Wasted (0 conv.): $%{y:,.0f}<extra></extra>",
    )

    if "hit_rate_pct" in df.columns:
        fig.add_scatter(
            name="Hit Rate %", x=labels, y=hit_rates,
            mode="lines+markers", yaxis="y2",
            line=dict(color="#7c3aed", width=2),
            hovertemplate="<b>%{x}</b><br>Hit rate: %{y:.1f}%<extra></extra>",
        )

    fig.add_hline(
        y=target_rate, yref="y2", line_dash="dash", line_color="#22c55e",
        annotation_text=f"Target {target_rate:.0f}%",
        annotation_position="top left",
    )

    scoreable_rates = [r for r in hit_rates if r is not None]
    y2_max = max(
        max(scoreable_rates) * 1.3 if scoreable_rates else target_rate,
        target_rate + 10,
        30,
    )
    y2_max = min(y2_max, 100)

    fig.update_layout(
        barmode="stack",
        title=dict(text=f"Spend by outcome per {window_d}-day cohort window", font=dict(size=13)),
        height=370, margin=dict(t=40, b=10),
        yaxis=dict(title="Spend ($)"),
        yaxis2=dict(overlaying="y", side="right", title="Hit Rate %", range=[0, y2_max]),
        legend=dict(orientation="h", y=-0.25),
    )
    st.plotly_chart(fig, use_container_width=True)

    if motion_ctx:
        st.caption(
            f"For context: Motion {data.get('spend_tier', '')} tier avg hit rate is {motion_ctx}% "
            "(their definition differs — not directly comparable to per-window CPA-percentile method above)."
        )


def chart_rolling_reach(data: dict):
    monthly = data.get("monthly_reach", [])
    warnings = data.get("data_warnings", [])
    calc_note = data.get("calculation_note", "")

    if not monthly:
        st.info("No reach data available.")
        return

    # Surface insufficient-data state without a verdict card
    if data.get("using_fallback") and data.get("signal_b_fired") is None:
        st.warning(warnings[0] if warnings else "Reach saturation cannot be measured — no M−12 baseline yet.")
        if calc_note:
            st.caption(calc_note)
    elif calc_note:
        st.caption(calc_note)

    df = pd.DataFrame(monthly)
    fig = go.Figure()
    fig.add_bar(name="Total Reach", x=df["month"], y=df.get("reach", []),
                marker_color="#60a5fa")
    fig.add_bar(name="Est. Net New Reach", x=df["month"], y=df.get("net_new_reach", []),
                marker_color="#f97316")
    if "cost_per_net_new" in df.columns:
        fig.add_scatter(name="Cost / Net New ($)", x=df["month"], y=df["cost_per_net_new"],
                        mode="lines+markers", yaxis="y2",
                        line=dict(color="#6366f1", width=2))

    # Signal threshold annotations
    prior_avg = data.get("prior_avg_cost_pnn")
    recent_avg = data.get("recent_avg_cost_pnn")
    if prior_avg and recent_avg:
        threshold = prior_avg * 1.20
        fig.add_hline(y=threshold, yref="y2", line_dash="dot", line_color="#ef4444",
                      annotation_text=f"Signal A threshold ({_fmt_usd(threshold)})",
                      annotation_position="top left")

    fig.update_layout(
        barmode="group", title="", height=360, margin=dict(t=10, b=10),
        yaxis2=dict(
            overlaying="y", side="right",
            title="Cost / Net-New Reach (USD)",
            tickprefix="$",
            tickformat=",.2f",
        ),
        legend=dict(orientation="h", y=-0.25),
    )
    st.plotly_chart(fig, use_container_width=True)

    # Signal summary below chart
    signal_a = data.get("signal_a_fired")
    signal_b = data.get("signal_b_fired")
    col1, col2 = st.columns(2)
    with col1:
        if signal_a is True:
            st.error(f"Signal A: Cost rising — {_fmt_usd(prior_avg)} → {_fmt_usd(recent_avg)} (+{(recent_avg/prior_avg-1)*100:.0f}%)")
        elif signal_a is False:
            st.success(f"Signal A: Cost stable — {_fmt_usd(prior_avg)} → {_fmt_usd(recent_avg)}")
        else:
            st.info("Signal A: Insufficient data")
    with col2:
        trailing = data.get("trailing_ratio")
        recent = data.get("recent_ratio")
        if signal_b is True:
            st.error(f"Signal B: Ratio dropping — {trailing*100:.0f}% → {recent*100:.0f}% net-new")
        elif signal_b is False:
            st.success(f"Signal B: Ratio stable — {trailing*100:.0f}% → {recent*100:.0f}% net-new")
        elif signal_b is None:
            st.info("Signal B: Suppressed — no M−12 baseline")


def chart_volume_vs_spend(data: dict):
    your_launches  = data.get("avg_monthly_launches", 0)
    motion_median  = data.get("motion_median_monthly", 0)
    top_quartile   = data.get("motion_top_quartile_monthly", 0)
    vertical       = data.get("vertical", "")
    tier           = data.get("tier", "")
    tier_range     = data.get("tier_spend_range", "")
    run_rate       = data.get("account_monthly_run_rate", 0)
    fallback_used  = data.get("fallback_used", False)
    med_label      = data.get("median_cohort_label", f"{vertical} × {tier}-tier accounts")
    topq_label     = data.get("top_quartile_cohort_label", f"All verticals × {tier}-tier accounts")
    cross_vertical = data.get("top_quartile_is_cross_vertical", True)
    launch_window  = data.get("launch_window", {})
    bench_source   = data.get("benchmark_source", "Motion 2026 Creative Benchmarks")

    window_label  = launch_window.get("label", "Last 3 months")
    window_months = launch_window.get("months", [])
    monthly_counts = launch_window.get("monthly_counts", [])

    if fallback_used:
        st.warning(f"⚠️ {vertical} benchmark suppressed for {tier} tier (insufficient sample). Showing all-verticals median instead.")

    run_rate_str = f"~${run_rate/1000:.0f}K/mo" if run_rate else ""
    bar_labels = [
        f"Your Launches<br>{run_rate_str}",
        f"{vertical} Median<br>{tier_range} cohort",
        f"Cross-Vertical Top Quartile<br>{tier_range} cohort",
    ]
    fig = go.Figure()
    fig.add_bar(name="Your Launches", x=[bar_labels[0]], y=[your_launches],
                marker_color="#1d4ed8")
    fig.add_bar(name=med_label, x=[bar_labels[1]], y=[motion_median],
                marker_color="#22c55e")
    # Different shade + pattern to signal different cohort definition
    fig.add_bar(name=topq_label, x=[bar_labels[2]], y=[top_quartile],
                marker=dict(color="#c084fc", pattern=dict(shape="/", fgcolor="#7e22ce")))

    fig.update_layout(
        title=dict(
            text=f"{window_label} vs Motion 2026 benchmarks · {tier} tier ({tier_range})",
            font=dict(size=13),
        ),
        height=320, margin=dict(t=40, b=10),
        yaxis_title="Avg monthly creatives launched",
        showlegend=False,
    )
    st.plotly_chart(fig, use_container_width=True)

    # Launch detail row
    if window_months and monthly_counts and len(window_months) == len(monthly_counts):
        detail = " · ".join(f"{m}: {c}" for m, c in zip(window_months, monthly_counts))
        st.caption(f"Launch counts — {detail}")

    if cross_vertical:
        st.caption("ⓘ Top-quartile bar is cross-vertical — Motion doesn't publish vertical-level quartiles.")
    st.caption(f"Source: {bench_source}")

    warnings = data.get("data_warnings", [])
    for w in warnings:
        st.caption(f"⚠️ {w}")

    # Tier reference table
    tier_table = data.get("tier_benchmark_table", [])
    if tier_table:
        st.markdown("**Where you sit across spend tiers:**")
        rows = []
        for row in tier_table:
            marker = " ← you" if row.get("is_current") else ""
            rows.append({
                "Spend tier": f"{row['tier']} ({row['spend_range']}){marker}",
                f"{vertical} median (monthly)": f"{row['median_monthly']:.0f}" if row.get('median_monthly') else "—",
            })
        st.table(rows)


def priority_action_stack(analyses: list[dict]):
    criticals  = [(a["title"], a["action"]) for a in analyses if a["verdict"] == "CRITICAL"]
    warnings   = [(a["title"], a["action"]) for a in analyses if a["verdict"] == "WARNING"]
    healthies  = [(a["title"], a["action"]) for a in analyses if a["verdict"] == "HEALTHY"]
    # INSUFFICIENT_DATA analyses are excluded from the priority stack — they're informational notes, not actions

    st.markdown("---")
    st.markdown("## Priority Action Stack")

    rank = 1
    if criticals:
        st.markdown("### 🔴 CRITICAL — do this week")
        for title, action in criticals[:2]:
            st.markdown(f"**{rank}. [{title}]** {action}")
            rank += 1

    if warnings:
        st.markdown("### 🟡 WARNING — do this month")
        for title, action in warnings[:2]:
            st.markdown(f"**{rank}. [{title}]** {action}")
            rank += 1

    if healthies:
        st.markdown("### 🟢 HEALTHY — keep doing")
        for title, action in healthies[:1]:
            st.markdown(f"**{rank}. [{title}]** {action}")


def main():
    st.set_page_config(page_title="Meta Account Diagnostics", layout="wide")

    results = load_results()
    config = results.get("config", {})
    run_date = results.get("run_date", str(date.today()))
    account_id = config.get("account_id", "unknown")
    conv_event = config.get("conversion_event", "conversion")
    conv_label = config.get("conversion_label", conv_event)

    st.title(f"Meta Account Diagnostics — {account_id} — {run_date}")
    st.subheader(f"Optimizing for: {conv_event} ({conv_label})")

    analyses = results.get("analyses", [])
    n_critical = sum(1 for a in analyses if a["verdict"] == "CRITICAL")
    n_warning  = sum(1 for a in analyses if a["verdict"] == "WARNING")
    n_healthy  = sum(1 for a in analyses if a["verdict"] == "HEALTHY")
    n_nodata   = sum(1 for a in analyses if a["verdict"] == "INSUFFICIENT_DATA")

    with st.sidebar:
        st.markdown("### Account Summary")
        overview = results.get("overview", {})
        st.metric("Total Spend (90d)", f"${_to_float(overview.get('spend', 0)):,.0f}")
        st.metric("Active Ads", overview.get("active_ads", "—"))
        st.metric("Date Range", overview.get("date_range", "last_90_days"))
        st.markdown("---")
        st.markdown("### Health Score")
        st.markdown(f"<span style='color:#ef4444;font-weight:700'>🔴 CRITICAL: {n_critical}</span>", unsafe_allow_html=True)
        st.markdown(f"<span style='color:#f59e0b;font-weight:700'>🟡 WARNING: {n_warning}</span>", unsafe_allow_html=True)
        st.markdown(f"<span style='color:#22c55e;font-weight:700'>🟢 HEALTHY: {n_healthy}</span>", unsafe_allow_html=True)
        if n_nodata:
            st.markdown(f"<span style='color:#6b7280;font-weight:700'>⚪ INSUFFICIENT DATA: {n_nodata}</span>", unsafe_allow_html=True)
        st.markdown("---")
        st.caption(f"Run date: {run_date}")

    chart_fns = {
        "test_and_learn":      chart_test_and_learn,
        "creative_allocation": chart_creative_allocation,
        "old_creative":        chart_old_creative,
        "creative_churn":      chart_creative_churn,
        "slugging_rate":       chart_slugging_rate,
        "rolling_reach":       chart_rolling_reach,
        "volume_vs_spend":     chart_volume_vs_spend,
    }

    for a in analyses:
        analysis_id = a.get("id", "")
        title   = a["title"]
        verdict = a["verdict"]
        meaning = a.get("meaning", "")
        action  = a.get("action", "")
        data    = a.get("data", {})

        def make_chart_fn(aid, d):
            fn = chart_fns.get(aid)
            return lambda: fn(d) if fn else st.info("Chart not available.")

        analysis_card(title, verdict, meaning, action, make_chart_fn(analysis_id, data))

    priority_action_stack(analyses)


if __name__ == "__main__":
    main()
